### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by sergiocorreia** [haghish/github#1]
Hi E.F.,

This looks incredibly useful. A few thoughts that I hope could be useful:

- I've had trouble on the past with packages installed from multiple places (e.g. from SSC, Github, local folders). There is a file called `stata.trk` in the ado/plus folder that often gets corrupted if you install a package from multiple places: on the second install, it fails to detect that it has already been installed from somewhere else; this makes the `ado uninstall ...` command fail for that package, and can also create issues if the files listed in both versions differ. Once the trk file is corrupt, you need to delete the entire plus folder (or if you are lucky and spotted it right away, replace it with `backup.trk`).
- A way to prevent this whole mess is to run this line `cap ado uninstall <package>` right before you try to install it.
- It might also be useful to generalize it or create a wrapper that allows github/ssc/local installs with the same commands. I often want to download a stable version (SSC), or just build a file locally, so having the same command for these ops helps a lot.
- Dependencies are incredibly useful, but I'm wondering how to deal with having more than one package in the same location. Maybe allow for `packagename_dependency.do`? (this might also help for packages that get published in SSC or in a centralized repo)

Cheers!
Sergio

**Comment by haghish** [comment]
Thanks for your comments. I think as soon as I add the journal article all of these will get clear. 
- you only corrupt the `trk` if you `force install` the package.
- uninstalling the package slows down the process for a few seconds... So it's not a good idea, and also, not necessary, I believe. 
- the `dependency.do` should not be installable. this is a file that is only hosted in the repository, but will not be copied. I make that clear in the documentation. In other words, it's a file that is executed after installing the repository, **if it exists**.
