### ISSUE TITLE
Package located in subfolder

### ISSUE THREAD

**Issue by sergiocorreia** [haghish/github#10]
I have a small question:

In all of my packages, I have the installation files in the `src` subfolder ([example](https://github.com/sergiocorreia/reghdfe/tree/master/src)). This is partly because there are often many files, including test file, docs, etc. so it helps to keep things organized.

Is there a way to install from a given subfolder?

Thanks!
Sergio

**Comment by haghish** [comment]
Yes you can. You have to edit your **pkg** file and add tthe subdirectory to the file names:

for example:

`f xxx.ado` should be `f src/xxx.ado`. It has worked before: https://github.com/haghish/github/issues/7
