### ISSUE TITLE
force or replace option

### ISSUE THREAD

**Issue by jpazvd** [haghish/github#11]
Is there any way I can have the github ado replacing the existing the version of the user-written version of the files? when using net install we have the three options.  

```
Possible things to do:

    1.  Forget it
        (best choice if any of the above files were written by you and just
        happen to have the same name or you do not want the originals changed)

    2.  Look for an already-installed package of the same name
        (which you might then choose to uninstall)

    3.  Search installed packages for the duplicate file(s) by clicking
        on the file names above

    4.  Force installation replacing already-installed files
        (if this is an update, this would be a safe choice; you will end
        up with the original and the update apparently installed, but it
        doesn't matter; you can even uninstall the original later)
```

It would be great to have the same functionality in the github ado

**Comment by Meiting-Wang** [comment]
I agree above. "github install" will install command without inquiry, though files have existed.

**Comment by haghish** [comment]
Please see this line of the program: https://github.com/haghish/github/blob/master/github.ado#L555

A few years ago, some people in the Stata List suggested to make sure the program is first uninstalled, so anytime you install a package, first there is an attempt to uninstall it, if it already exists on the machine. 

This was not how I wanted it to be, but the community encouraged it!
