### ISSUE TITLE
Download count?

### ISSUE THREAD

**Issue by mtyszler** [haghish/github#15]
Dear @haghish 

As a supplier of stata package, I'd like to know how many times my package has been downloaded/installed. 

For packages installed via `ssc` we can use https://ideas.repec.org/c/boc/bocode/s457967.html

Are you aware of anything equivalent for `github` ?

**Comment by haghish** [comment]
Up to the latest update of the `github` package, I checked the GitHub API and there was still no such thing available for all repositories. GitHub provides download count only for downloading binaries, so far... 

On `github search`, I rank the packages based on their stars and forks, which also gives an idea about the popularity of a repository. It's not the same, but it's an indication...

**Comment by mtyszler** [comment]
Thanks a lot or the added info
