### ISSUE TITLE
Can it support the use of a proxy?

### ISSUE THREAD

**Issue by yanyu2015** [haghish/github#28]
Due to certain reasons, I often encounter network issues that prevent me from completing package installations using this command. 
```
remote connection failed
```
I'm unsure how to resolve this. Can it support proxy settings or automatically use the default proxy settings?

**Comment by haghish** [comment]
This seem to be a limitation for Stata rather than github package or your work environment. It depends on your Stata version as well, because some of the old Stata versions had such a known problem. Please contact Stata support and if they recommend a change in the code, make a suggestion here.
