### ISSUE TITLE
Error 133 unknown function ustrlower()

### ISSUE THREAD

**Issue by glennsandstrom** [haghish/github#3]
github command is throwing and error all the time when I try to install something and I cant figure out why.

```
. github install haghish/markdoc, version(3.9.6) replace 
unknown function ustrlower()
r(133);
```

Stata version 13.1
Windows 10 professional.

**Comment by aalexandersson** [comment]
What did you type in Stata, and what is Stata's error message?

**Comment by glennsandstrom** [comment]
The code and errormessage in my post above. Any call to github install results in r133) "unkown function ustrlower()"

**Comment by aalexandersson** [comment]
Glenn,

Sorry about that. Your post did not appear in full in my email; I can see
your post in full at https://github.com/haghish/github/issues/3.
Anyway, it looks like a temporary bug in github. Temporary because I cannot
reproduce the error message. The software installs fine, according to the
output. I am using Stata 14.2 on Windows 7.

Anders

**Comment by glennsandstrom** [comment]
OK, thanks for you input. I have not tried it on my home computer and will do that tonight. However, I have the same setup at home so I anticipate that it will be the same issue there. However, I have a Macbook for my mobile needs and I can try an see if the error goes away if I use that platform.

**Comment by glennsandstrom** [comment]
So I found the cause of the error. On line 317 in github.ado there is a function-call to:

`local anything : display ustrlower(`"`anything'"')`

This function is a unicode aware function that is not availiable in Stata 13. That is why I am getting the error and you are not. This is proabably why I am having so much trouble getting both github and markdoc to work properly. I guess I will have to wait until I update Stata. I was planning on wating until Stata 15 is released as it is quite a big cost upgrading.

**Comment by haghish** [comment]
yes, the function is only available in Stata 14, unfortunately. I am aware of this limit, but the workaround for avoiding this function was problematic...

**Comment by glennsandstrom** [comment]
OK, so system requirements are and will be Stata 14 (or later) for markdoc and/or github?

**Comment by haghish** [comment]
right, but I don't think that's the case for github.
