### ISSUE TITLE
github update user/repro causes error

### ISSUE THREAD

**Issue by glennsandstrom** [haghish/github#5]
Trying to run the update routine causes following error using version 1.4.1

package was not found
file https://api.github.com/repos//contents not found

The program is aware of the pkg being installed on my system but refuses to update it.

. github list
 ----------------------------------------------------------------
  Date         Name        user/repository     Action
 ----------------------------------------------------------------
 23 Nov 2018   estimates_table_docxglennsandstrom/est~dupdate / uninstall
 ----------------------------------------------------------------

**Comment by haghish** [comment]
can you please provide the code you run? 

There was a fatal error in the previous release that was fixed a few days ago.  **currently, it's version 1.4.5**, see if uninstalling and reinstalling `github` will fix the problem (I hope)

**Comment by glennsandstrom** [comment]
I am using your program v.1.4.1 on Windows

I was just fiddling around with a package I have put here on github (glennsandstrom/estimates_table_docx) that I just pushed a small bug fix to going from v.1.0 to 1.1

I made sure I had installed the program by github install glennsandstrom/estimates_table_docx

running
github list

. github list
 ----------------------------------------------------------------
  Date         Name        user/repository     Action
 ----------------------------------------------------------------
 23 Nov 2018   estimates_table_docxglennsandstrom/est~dupdate / uninstall
 ----------------------------------------------------------------

running 

github update glennsandstrom/estimates_table_docx

gives following: 

glennsandstrom/estimates_table_docx package was not found
file https://api.github.com/repos//contents not found

**Comment by haghish** [comment]
Your syntax is wrong. 

try: 

    github update packagename

Github memorizes the username, so you only need the package name... please confirm this solves your problem

**Comment by glennsandstrom** [comment]
Thanks!! Sorry for not being able to read the manual. I used the username/package-name idiom.
Suggestion... it would be nice to see the version of the package you have installed when you run:
`github list`
Or maybe when you run update and you have an outdated version on your system something like:
installed version is v.X.X updating to v.Y.Y

Many thanks for the support.

Best,

Glenn Sandström

**Comment by haghish** [comment]
Stata package versioning is a mess. But I can make a call from the "releases" you make and add that to the package. I will also fix the problem you faced above in the future releases, namely, if someone also puts the username, it should move on and update the package. 

PS, I checked out your repository, nice stuff!
