### ISSUE TITLE
MAKEDLG: question regarding TOC and PKG generation 

### ISSUE THREAD

**Issue by jpazvd** [haghish/github#7]
Is it possible to pull files from a sub directory within my GitHub repository.

My stata ado files are organized in the following structure

.../src/a
.../src/e
.../src/_

I would like to generate a pkg which would allow me to files from sub directories within my REPO.
Is that possible? or all fields need to be in the root directory?

I have used the following syntax to make my TOC and PKG:

makedlg adecomp, ///
	replace toc pkg title(`"ADECOMP: Stata module to estimate Shapley Decomposition by Components of a Welfare Measure"') ///
	version("1.1") license("MIT") author("Joao Pedro Azevedo") affiliation("World Bank") ///
	url("http://www.worldbank.org/en/about/people/j/joao-pedro-azevedo") ///
	email("jazevedo@worldbank.org") ///
	install(`""C:\Users\wb255520\Documents\myados\adecomp\src\a\adecomp.ado"  "C:\Users\wb255520\Documents\myados\adecomp\src\a\adecomp.sthlp" "C:\Users\wb255520\Documents\myados\adecomp\src\_\_ex_adecomp.ado""') ///
	ancillary(`""C:\Users\wb255520\Documents\myados\adecomp\src\e\exdata_adecomp.dta""')

Best regards,

JP

**Comment by haghish** [comment]
At the time I was developing `makedlg`, I thought about it. My final thought was to keep the program as simple as possible. To allow what you are asking for, I needed to get the working directory of the repository and then remove the similarities between the paths. But then, there is  other complications, namely, the URL might be different on GitHub (but I am not very sure). You could try editing the **pkg** file by adding the sub-directories before `F filename.ado` and see if it works. 

I know it can be done...

**Comment by jpazvd** [comment]
I have tried by simply adding the folder structure (from a root).

I replaced

f a.ado

by

f src/a/a.ado

I think it has worked.

Best,

JP
