### ISSUE TITLE
command abspath is unrecognized

### ISSUE THREAD

**Issue by luispfonseca** [haghish/github#8]
After calling the `dbmake` command and filling in the options, Stata runs the `makedlg` command and I get the following error:
```
command abspath is unrecognized
```

A quick google search showed me that your package [markdoc](https://github.com/haghish/markdoc) includes the `abspath` command, so I installed it with `gitget markdoc` and `makedlg` ran without issue. You might want to fix this dependency.

Thank you for your work!

**Comment by haghish** [comment]
thank you for discovering this bug. You're very right. I fixed the bug, cheers.
